# Generated by Django 2.2.3 on 2019-08-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180406_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='tags',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
