# Generated by Django 2.2.3 on 2019-08-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_albumimage_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumimage',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='tags',
        ),
    ]
